export enum ActionTypesEnum {
  CREATE_NEW_QUESTION = "CREATE_NEW_QUESTION",
  RECEIVE_CREATED_QUESTION = "UPDATE_QUESTIONS_AFTER_CREATE",

  REQUEST_QUESTIONS_LIST = "REQUEST_QUESTIONS_LIST",
  RECEIVE_QUESTIONS_LIST = "RECEIVE_QUESTIONS_LIST",
}
